version: "3.9"

services:
  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db/sonar
    volumes:
      - /Users/psaho01/Downloads/sonar/sonarqube_conf:/opt/sonarqube/conf
      - /Users/psaho01/Downloads/sonar/sonarqube_data:/opt/sonarqube/data
      - /Users/psaho01/Downloads/sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - /Users/psaho01/Downloads/sonar/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres:12
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /Users/psaho01/Downloads/sonar/postgresql:/var/lib/postgresql
      - /Users/psaho01/Downloads/sonar/postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
